# Generated by Django 3.2 on 2023-04-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loan', to='loan_system.lector'),
        ),
    ]
