# Generated by Django 3.2 on 2023-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_system', '0002_alter_loan_lector'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
