# Generated by Django 3.2 on 2023-04-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_category'),
        ('loan_system', '0003_lector_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loan', to='book.book'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_system.lector'),
        ),
    ]
